name: puzzle_daily
description: The Dailies - A daily puzzle game featuring Sudoku, Killer Sudoku, Crossword, and Word Search.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.1
  http: ^1.1.0
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  flutter_animate: ^4.3.0
  google_fonts: ^6.1.0
  confetti: ^0.7.0
  vibration: ^2.0.0
  audioplayers: ^5.2.1
  google_mobile_ads: ^5.1.0
  in_app_purchase: ^3.2.0
  package_info_plus: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/sounds/
    - assets/images/

  fonts:
    - family: SpaceMono
      fonts:
        - asset: assets/fonts/SpaceMono-Regular.ttf
        - asset: assets/fonts/SpaceMono-Bold.ttf
          weight: 700
